"""fechas de inicio y cierre de caso

Revision ID: 346d4fb31680
Revises: 68712c76840e
Create Date: 2026-06-07 02:45:55.417975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346d4fb31680'
down_revision = '68712c76840e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iniciado', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cerrado_en', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casos', schema=None) as batch_op:
        batch_op.drop_column('cerrado_en')
        batch_op.drop_column('iniciado')

    # ### end Alembic commands ###
