"""origen de documento

Revision ID: 3ecb6945d413
Revises: 723a87a200ad
Create Date: 2026-06-07 12:41:44.408823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ecb6945d413'
down_revision = '723a87a200ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_column('origen')

    # ### end Alembic commands ###
