"""tabla de notificaciones

Revision ID: 58dc372a2c71
Revises: ba1b78c6530c
Create Date: 2026-06-05 21:24:33.145311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dc372a2c71'
down_revision = 'ba1b78c6530c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('seccion', sa.String(length=20), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_notificaciones_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificaciones'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
