"""marca de metodo de pago

Revision ID: 68712c76840e
Revises: fb1af2543c7a
Create Date: 2026-06-07 02:14:01.695493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68712c76840e'
down_revision = 'fb1af2543c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
