"""responde_a en mensajes

Revision ID: 6d7abdda65ad
Revises: 58dc372a2c71
Create Date: 2026-06-05 21:32:51.898732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7abdda65ad'
down_revision = '58dc372a2c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responde_a_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_mensajes_responde_a_id_mensajes'), 'mensajes', ['responde_a_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mensajes_responde_a_id_mensajes'), type_='foreignkey')
        batch_op.drop_column('responde_a_id')

    # ### end Alembic commands ###
