"""tabla de eventos de caso

Revision ID: 723a87a200ad
Revises: 346d4fb31680
Create Date: 2026-06-07 02:48:59.234577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723a87a200ad'
down_revision = '346d4fb31680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_caso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], name=op.f('fk_eventos_caso_caso_id_casos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eventos_caso'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos_caso')
    # ### end Alembic commands ###
