"""esquema inicial

Revision ID: ba1b78c6530c
Revises: 
Create Date: 2026-06-05 21:15:01.758869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1b78c6530c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('abogado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abogado_id'], ['usuarios.id'], name=op.f('fk_usuarios_abogado_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_table('casos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=True),
    sa.Column('abogado', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('actualizado', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_casos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_casos'))
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('vencimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_facturas_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facturas'))
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('abogado_id', sa.Integer(), nullable=True),
    sa.Column('remitente', sa.String(length=120), nullable=True),
    sa.Column('es_cliente', sa.Boolean(), nullable=True),
    sa.Column('asunto', sa.String(length=200), nullable=True),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('enviado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['abogado_id'], ['usuarios.id'], name=op.f('fk_mensajes_abogado_id_usuarios')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_mensajes_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensajes'))
    )
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('detalle', sa.String(length=120), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_metodos_pago_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metodos_pago'))
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('tamano', sa.String(length=40), nullable=True),
    sa.Column('subido', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], name=op.f('fk_documentos_caso_id_casos')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_documentos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    op.drop_table('metodos_pago')
    op.drop_table('mensajes')
    op.drop_table('facturas')
    op.drop_table('casos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
