"""tabla de citas

Revision ID: e06edca8a35d
Revises: 6d7abdda65ad
Create Date: 2026-06-07 01:35:19.886496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06edca8a35d'
down_revision = '6d7abdda65ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abogado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['abogado_id'], ['usuarios.id'], name=op.f('fk_citas_abogado_id_usuarios')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_citas_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citas')
    # ### end Alembic commands ###
