"""registro de pago en factura

Revision ID: fb1af2543c7a
Revises: e06edca8a35d
Create Date: 2026-06-07 02:09:21.562032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1af2543c7a'
down_revision = 'e06edca8a35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pagada_en', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_facturas_metodo_pago_id_metodos_pago'), 'metodos_pago', ['metodo_pago_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_facturas_metodo_pago_id_metodos_pago'), type_='foreignkey')
        batch_op.drop_column('pagada_en')
        batch_op.drop_column('metodo_pago_id')

    # ### end Alembic commands ###
